name: residents_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.3.0
  image_picker: ^0.8.5+3  # Mantener la versión más reciente
  firebase_storage: ^12.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
