// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDclO-uiYF1n511mO2yHdIszH0LZ6dVRro',
    appId: '1:946464443279:android:ee23e9bdb1b6cfc01899fa',
    messagingSenderId: '946464443279',
    projectId: 'platziblog-bc8f5',
    storageBucket: 'platziblog-bc8f5.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmzqLHgi7GztbL_IuPflNaR603uMHsRk',
    appId: '1:946464443279:web:ebadff270935a4021899fa',
    messagingSenderId: '946464443279',
    projectId: 'platziblog-bc8f5',
    authDomain: 'platziblog-bc8f5.firebaseapp.com',
    storageBucket: 'platziblog-bc8f5.appspot.com',
    measurementId: 'G-G0NQHV6NKW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0q6ezJQ82CF9SSPsjG9d0Ti8gKI3atc',
    appId: '1:946464443279:ios:685f1c7ad35c225e1899fa',
    messagingSenderId: '946464443279',
    projectId: 'platziblog-bc8f5',
    storageBucket: 'platziblog-bc8f5.appspot.com',
    iosBundleId: 'com.example.residentsApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0q6ezJQ82CF9SSPsjG9d0Ti8gKI3atc',
    appId: '1:946464443279:ios:685f1c7ad35c225e1899fa',
    messagingSenderId: '946464443279',
    projectId: 'platziblog-bc8f5',
    storageBucket: 'platziblog-bc8f5.appspot.com',
    iosBundleId: 'com.example.residentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmzqLHgi7GztbL_IuPflNaR603uMHsRk',
    appId: '1:946464443279:web:3208a52212505e661899fa',
    messagingSenderId: '946464443279',
    projectId: 'platziblog-bc8f5',
    authDomain: 'platziblog-bc8f5.firebaseapp.com',
    storageBucket: 'platziblog-bc8f5.appspot.com',
    measurementId: 'G-Z3BVRYV8RT',
  );

}